### ISSUE TITLE
missing docker images with nginx tag

### ISSUE THREAD

**Issue by mbenecke** [xwiki-labs/cryptpad-docker#11]
Hi,

just a tiny one, if failed if you try to use Cryptpad as suggested in the README:

``` ✦ ❯ docker run -d -e "CPAD_MAIN_DOMAIN=example.com" -e "CPAD_SANDBOX_DOMAIN=sandbox.example.com" -p 80:80 promasu/cryptpad:nginx
Unable to find image 'promasu/cryptpad:nginx' locally
docker: Error response from daemon: manifest for promasu/cryptpad:nginx not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

You have to use **promasu/cryptpad:v3.9.0-nginx**  which is [JamaicanMonkey](https://github.com/xwiki-labs/cryptpad/releases/tag/3.9.0) 

``` ✦ ❯ docker run -d -e "CPAD_MAIN_DOMAIN=example.com" -e "CPAD_SANDBOX_DOMAIN=sandbox.example.com" -p 80:80 promasu/cryptpad:v3.9.0-nginx
Unable to find image 'promasu/cryptpad:v3.9.0-nginx' locally
v3.9.0-nginx: Pulling from promasu/cryptpad
...
4bea59e4e7f9: Pull complete
Digest: sha256:c9dd26f449769caedd94d3993abc716ec034b485c871576b7bca0abb0c268698
Status: Downloaded newer image for promasu/cryptpad:v3.9.0-nginx
48447ad6147f1268d3b80cfb537c92e4a08d26aefae4b0af8cf6224817dcc575

~ took 38s
✦ ❯ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS                         NAMES
48447ad6147f   promasu/cryptpad:v3.9.0-nginx   "/bin/sh /docker-ent…"   19 seconds ago   Up 13 seconds   0.0.0.0:80->80/tcp, 443/tcp   cool_bhaskara
```

**Comment by promasu** [comment]
I still need to do a rewrite of my CI to push "latest", "alpine", "nginx" and "nginx-alpine". Will do tomorrow.

I nevertheless strongly advise to use **promasu/cryptpad:v3.25.1-nginx**

Version 3.9.0 of CryptPad is outdated!

**Comment by goost** [comment]
I could not find the nginx tag today too, `hub.docker.com/r/promasu/cryptpad` shows a bunch of tags updated a few hours ago but no 'nginx' for a quick latest version of the nginx based container.

**Comment by promasu** [comment]
I'm really really sorry but I finally managed to get my CI upload the right images.
Thus promasu/cryptpad:nginx is available now!
