### ISSUE TITLE
HTTP headers bug - /api/config duplicate headers

### ISSUE THREAD

**Issue by Asharas** [xwiki-labs/cryptpad-docker#14]
Responses to /api/config calls have some duplicate headers (CSP, CORS, etc).
Some headers like `Content-Type` aren't.  

This seems to cause the site to stop working on some stricter browser configurations.  

#### Steps to reproduce  
Build the nginx version of the image with `docker build -t cryptpad:nginx -f Dockerfile-nginx .`.  

Set `httpUnsafeOrigin` and `httpSafeOrigin` in `config.js` then run the image.

`docker run --rm -it -e CPAD_MAIN_DOMAIN=pad.lan.example.com -e CPAD_SANDBOX_DOMAIN=sb.pad.example.com -e CPAD_HTTP2_DISABLE="true" -v $(pwd)/config.js:/cryptpad/config/config.js -p 80:80 cryptpad:nginx`  

Open your browser and its network console, go to the cryptpad instance and look for `/api/config` in the console

  

I am trying to find a solution but with no avail so any insight is welcome.

**Comment by Asharas** [comment]
After some search I found that an issue has already been opened upstream.  
https://github.com/xwiki-labs/cryptpad/issues/633

**Comment by promasu** [comment]
The aboved linked issue is already closed but the issue seems to persist.
See xwiki-labs/cryptpad#694

**Comment by Asharas** [comment]
I'll try to find some time in the upcoming week to write a workaround in the entrypoint script of the image. 
It will be an ugly, but it will work.

**Comment by promasu** [comment]
I this still a problem?

**Comment by Asharas** [comment]
As far as I can tell, headers are not duplicated anymore, PR #16 may be closed
