### ISSUE TITLE
'Uncaught EvalErrors' for Spreadsheets

### ISSUE THREAD

**Issue by longestmt** [xwiki-labs/cryptpad-docker#19]
Server: Ubuntu 18.04
Installation: Docker (Compose)

I've managed to get cryptpad up and running on my own domain. I had unusual issues with docker not being able to create directories so I had to use chmod to alter permissions for this app.

As far as I can tell everything is working fine except for spreadsheets. When I try to create or access a spreadsheet I get this error.

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' resource: sub.domain.xyz".`

I don't see any reports of this error online. It doesn't seem like there is a large selfhosted community for this application... yet :)

Kindly seeking help as to what could be causing this error.

Docker-compose:

>    cryptpad:
>     image: "promasu/cryptpad:nginx"
>     hostname: cryptpad
>     container_name: cryptpad
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - CPAD_MAIN_DOMAIN=sub.domain.xyz
>       - CPAD_SANDBOX_DOMAIN=sandbox.domain.xyz
>       # Traefik can't use HTTP2 to communicate with cryptpat_websocket
>       # A workaroung is disabling HTTP2 in Nginx
>       - CPAD_HTTP2_DISABLE=true
>     volumes:
>       - ./cryptpad/blob:/cryptpad/blob
>       - ./cryptpad/block:/cryptpad/block
>       - ./cryptpad/customize:/cryptpad/customize
>       - ./cryptpad/data:/cryptpad/data
>       - ./cryptpad/files:/cryptpad/datastore
>       - ./cryptpad/config.js:/cryptpad/config/config.js
>     ports:
>       - "780:80"
>       - "7443:443"
>     expose:
>       - "780"
>       - "7443"
>     ulimits:
>       nofile:
>         soft: 1000000
>         hard: 1000000
>

**Comment by promasu** [comment]
This repository is only for providing the community maintained files for a deployment with docker.
For any issues with the application which are not related to the kind of deployment, head over to the application repository https://github.com/xwiki-labs/cryptpad
