### ISSUE TITLE
Administration Panel?

### ISSUE THREAD

**Issue by longestmt** [xwiki-labs/cryptpad-docker#20]
I recently stood up a (mostly) functioning cryptpad instance. (Thank you guys for such a great product)

My question is regarding administration. Is there an administration portal I can access? It looks like the [administration documentation](https://docs.cryptpad.fr/en/admin_guide/index.html) has not been written (perhaps I could help there!).

I'd like to do the following:

1. Disable sign-ups (Preferably I'd like to send invitation links to my users)
2. Increase storage space per user

I'm comfortable with editing a config file if there isn't an administration portal.

Thanks!

**Comment by promasu** [comment]
This repository is only for providing the community maintained files for a deployment with docker.
For any issues with the application which are not related to the kind of deployment, head over to the application repository https://github.com/xwiki-labs/cryptpad
