### ISSUE TITLE
Sandbox configuration: loading via httpUnsafeOrigin

### ISSUE THREAD

**Issue by longestmt** [xwiki-labs/cryptpad-docker#22]
Posting this issue here specifically because I believe it is related to:

>       - CPAD_HTTP2_DISABLE=true

When I go to cryptpad.domain.xyz/checkup I get the following errors -- 

![image](https://user-images.githubusercontent.com/1509654/117088878-bd83f580-ad21-11eb-839a-06ca8b95e57d.png)

I'm using Caddy reverse proxy -- when I enable http2 I receive a 'server misbehaving' error.

Any idea how to resolve this issue?

**Comment by promasu** [comment]
Does the same thing happen when using nginx?
Is a safeOrigin set inside your cryptpad Config?
Is your webserver configured accordingly?
Which image are you using?
