### ISSUE TITLE
Email annouces next version ahead of time

### ISSUE THREAD

**Issue by diolwe** [xwiki-labs/cryptpad-docker#25]
Not really a technical issue but maybe something about internal project coordination?

I received an email by Aaron MacSween CryptPad project lead today, informing me about a new version of CPad with words like

> This is a one-time email to encourage you to update your instance. The version released on June 16th includes improvements for administrators and a new way to consent to future security notices.
> CryptPad has been very actively developed for the last few years. Depending on the version you are running you may be missing out on features or **exposed to security flaws**.

Fearful as I am I updated ... not. The docker release is still 4.6.0.

**Comment by ansuz** [comment]
Hi,

I sent that email. [4.7.0](https://github.com/xwiki-labs/cryptpad/releases/tag/4.7.0) is available in the official platform repository. This docker repository is maintained by volunteers, as indicated in the readme, and as such is sometimes not always up to date.

**Comment by diolwe** [comment]
... and the docker version does not differentiate by itself / does not "know" it is dockered ... but triggers the message none the less. OK. Understood. Thank you for clearing that up. I will wait for the docker version (and update my other instances which, by the way, did not trigger this mail).

**Comment by promasu** [comment]
Just commited 597f3bff82924203ccfe0a87ad96095b1c1a9311 and started the builds for the images. They should be around in some time
