### ISSUE TITLE
Upgrade to 4.11

### ISSUE THREAD

**Issue by almereyda** [xwiki-labs/cryptpad-docker#30]
The list of available tags and latest commits here indicate the latest release to be 4.10 https://hub.docker.com/r/promasu/cryptpad/tags?page=1&ordering=last_updated

We would like to track the upstream releases https://github.com/xwiki-labs/cryptpad/releases which are currently at 4.11

**Comment by almereyda** [comment]
This would mean to forward the submodule to https://github.com/xwiki-labs/cryptpad/commit/390e38acf63a9d7ae581eaa926ea678a519fcc14

**Comment by promasu** [comment]
Fixed with 297a9ef882812d7dba2570392a84e6dd3769859c

Build currently in progress.

**Comment by almereyda** [comment]
All of the thanks.

This has now become available as https://hub.docker.com/r/promasu/cryptpad/tags?page=1&ordering=last_updated&name=4.11
