### ISSUE TITLE
Failed upload with files larger than 300MB

### ISSUE THREAD

**Issue by gabrielpreite** [xwiki-labs/cryptpad-docker#31]
When uploading a file larger than 300MB (I tried .txt, .mkv and .mp4 files) the web page freezes and disconnects from the server after ~30 seconds. A snapshot of the page memory shows a size of 300+MB, the whole file plus the page base size.
Self hosted promasu/cryptpad on Unraid 6.9.2, docker version 4.12.0

Smaller files upload without issues, but after a failed attempt with a large one uploading stops working until i reload my page.

Upload limit is set at 1GB and max storage for my user is 200GB.

**Comment by promasu** [comment]
See https://github.com/xwiki-labs/cryptpad/issues/828
