### ISSUE TITLE
[nginx-alpine] multiple IPs for CPAD_TRUSTED_PROXY

### ISSUE THREAD

**Issue by Loader009** [xwiki-labs/cryptpad-docker#36]
I use two reverse proxies in chain (one for real IPs and another one for internal connection to shut off cryptpad).

It doesn't matter how I put two IPs in the __CPAD_TRUSTED_PROXY__ field (comma- or space-separated), I get an error and nginx/the whole container dies.

`nginx: [emerg] host not found in set_real_ip_from "10.89.6.2,10.89.9.2" in /etc/nginx/conf.d/cryptpad.conf:11`
`nginx: [emerg] invalid number of arguments in "set_real_ip_from" directive in /etc/nginx/conf.d/cryptpad.conf:11`

Do you think a fix is possible?

**Comment by almereyda** [comment]
You will want to put one configuration per line, as per the documentation.

Reference:

- https://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by Loader009** [comment]
Then you would need a for-loop for the nginx config in the nginx images?

I want to use the nginx images to ease maintenance, I am a lone admin for a server with a little bunch of services - thus to lower the maintenance is first priority for me right now.
