### ISSUE TITLE
Error creating data subfolders

### ISSUE THREAD

**Issue by lupa18** [xwiki-labs/cryptpad-docker#4]
Hello, 
I ran docker-compose up
and got this error (for each folder at _data_)
```
[Error: EACCES: permission denied, mkdir '/cryptpad/data/logs'] {
errno: -13,
code: 'EACCES',
syscall: 'mkdir',
path: '/cryptpad/data/logs'
 }
```

**Comment by promasu** [comment]
You have to give the local folders the correct permissions (see: https://github.com/xwiki-labs/cryptpad-docker#general-notices)

**Comment by lupa18** [comment]
First, thanks for your answer.

So, since is the first time I will run, I must do it twice: 
**1.** Fisrt time, for creating data folder (parent) that crashes. Then change permissions as described in your link
**2.** And up it again and it will work.
