### ISSUE TITLE
[nginx-alpine] cryptpad broken (cryptpad_websocket - connection refused)

### ISSUE THREAD

**Issue by Loader009** [xwiki-labs/cryptpad-docker#40]
I tried to find all errors, I have corrected all of them - but I don't know why I can't login - why the websocket doesn't accept connections.

```
[error] 6#6: *105 connect() failed (111: Connection refused) while connecting to upstream, client: clientip, server: cryptpad.mydomain, request: "GET /cryptpad_websocket HTTP/1.1", upstream: "http://[::1]:3000/cryptpad_websocket", host: "cryptpad.mydomain"
```

Any idea or experience with this?

**Comment by Loader009** [comment]
I'm gonna give up cryptpad, since I don't have a real usecase for that - and other services are enough for my usecases.
Thus I'm closing this.

I am letting the other issues open, just in case you decide to work on that.

**Comment by almereyda** [comment]
This might have been caused by an external reverse proxy trying to negotiate for HTTP/2 with Cryptpad's `nginx`.

Please also see https://github.com/xwiki-labs/cryptpad-docker/blob/72dd7030c1dc1c70b5ff3f53b8451f5af19a2927/README.md#Use-the-Nginx-version-with-Traefik

**Comment by Loader009** [comment]
I had disabled http2 by the env variable for that.
The issue was, I could open the site - but after entering the credentials and logging in (I migrated the data), the hashing was performed but after some time nothinf visible happened. I had failing messages in the firefox debugger window and found these lines in the logs of the container.

**Comment by almereyda** [comment]
Thanks for the note.
