### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [xwiki-labs/cryptpad-docker#44]
I'm trying to get cryptpad running on my homeserver. No traefik, no ngnix, nothing, just a simply cryptpad with http://localhost:3050 .

My docker-compose.yml

    ---
    version: '3.3'
    services:
        cryptpad:
            image: promasu/cryptpad:alpine
            container_name: cryptpad
            restart: always
            labels:
                - deunhealth.restart.on.unhealthy=true
            ports:
                - 3051:3000
                - 3052:3001
            volumes:
                - /home/somedude/docker-data/cryptpad/blob:/cryptpad/blob
                - /home/somedude/docker-data/cryptpad/block:/cryptpad/block
                - /home/somedude/docker-data/cryptpad/customize:/cryptpad/customize
                - /home/somedude/docker-data/cryptpad/data:/cryptpad/data
                - /home/somedude/docker-data/cryptpad/files:/cryptpad/datastore
    networks:
      default:
        name: dockernet
        external: true

Getting this:

    today at 03:31:23> cryptpad@4.12.1 start /cryptpad
    today at 03:31:23> node server.js
    today at 03:31:23
    today at 03:31:23Config not found, loading the example config. You can customize the configuration by copying config/config.example.js to ../config/config.js
    today at 03:31:23Serving content for http://localhost:3000/ via http://0.0.0.0:3000.
    today at 03:31:23
    today at 03:31:23Your instance is not correctly configured for safe use in production.
    today at 03:31:23See http://localhost:3000/checkup/ for more information.
    today at 03:31:23
    today at 03:31:23/cryptpad/lib/log.js:93
    today at 03:31:23            throw err;
    today at 03:31:23            ^
    today at 03:31:23
    today at 03:31:23[Error: EACCES: permission denied, mkdir '/cryptpad/data/logs'] {
    today at 03:31:23  errno: -13,
    today at 03:31:23  code: 'EACCES',
    today at 03:31:23  syscall: 'mkdir',
    today at 03:31:23  path: '/cryptpad/data/logs'
    today at 03:31:23}
    today at 03:31:23npm ERR! code ELIFECYCLE
    today at 03:31:23npm ERR! errno 1
    today at 03:31:23npm ERR! cryptpad@4.12.1 start: `node server.js`
    today at 03:31:23npm ERR! Exit status 1
    today at 03:31:23npm ERR! 
    today at 03:31:23npm ERR! Failed at the cryptpad@4.12.1 start script.
    today at 03:31:23npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    today at 03:31:23
    today at 03:31:23npm ERR! A complete log of this run can be found in:
    today at 03:31:23npm ERR!     /cryptpad/.npm/_logs/2022-03-03T02_31_23_296Z-debug.log
    today at 03:31:22Container stopped

I'm pretty sure it's a `chown -R somedude:somedude /home/somedude/docker-data/cryptpad/`

or maybe a

    environment:
        - USER_UID=1000
        - USER_GID=1000

issue, I dunno. But none of these help. What do?

**Comment by PiDroid-B** [comment]
Hello

you have to `chown -R 4001:4001` your volumes
this is the uid:gid used by the dockerfile
https://github.com/xwiki-labs/cryptpad-docker/blob/main/Dockerfile-alpine#L27

It will be great that environment variables allow to define them

**Comment by brunomgalmeida** [comment]
In case it helps someone, we can overcome this by building the image ourselvess and changing the ID

docker-compose.yml
```yaml
    # image: promasu/cryptpad
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PGID: 1000
        PUID: 1000
```

Dockerfile
```sh
FROM promasu/cryptpad

ARG PGID=4001
ARG PUID=4001

USER root

# Change the ID of node to be something else rather than the one we are trying to map
RUN groupmod -g 425 node && usermod -u 425 -g 425 node

# Change the ID of crytpad for permission
# This takes some time
RUN groupmod -g $PGID cryptpad && usermod -u $PUID -g $PGID cryptpad
```
