### ISSUE TITLE
dockerhub image versions trouble with v4.14.1 

### ISSUE THREAD

**Issue by parisni** [xwiki-labs/cryptpad-docker#52]
hi 

first of all, thanks for the good work achieved. 

I tried the `promasu/cryptpad:v4.14.1 *` and it turns out the 5.1.0 version is present in them. The logs says:

```
cryptpad-cryptpad-1  |
cryptpad-cryptpad-1  | > cryptpad@5.1.0 start
cryptpad-cryptpad-1  | > node server.js
```

as a workaround, I built my self the 4.14.1 and all good now

```
cryptpad-cryptpad-1  |
cryptpad-cryptpad-1  | > cryptpad@4.14.1 start
cryptpad-cryptpad-1  | > node server.js
```

**Comment by promasu** [comment]
There was an issue with my CI pipeline. Just fixed it and started a new build. A fixed image should be available in around two hours. Sorry for the problems
