### ISSUE TITLE
Deletion of Teams Drive

### ISSUE THREAD

**Issue by aconite33** [xwiki-labs/cryptpad-docker#53]
### Description

When running a local instance of Cryptpad, unable to delete a Teams Drive after the creation.

On clicking the "DELETE" button, no request is sent to the server side (Attached to the Docker window looking for any new requests to the Nginx server).

I have tried leaving the window open after clicking Delete for 2+ Hours and no resolution.

I am running a custom size of my teams drive (1 GB).

### Steps to reproduce

1. Create a Teams Drive
2. Create documents in Teams Drive
3. Browse to Team
4. Click on Administration as the Owner of the Teams Drive
5. Click "DELETE"
6. Validate that the Teams Drive never deletes and only feedback is constant spinning wheel

### Expected behavior

Deleting the Teams Drive as the Owner of the Team should delete the Teams Drive

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Ubuntu 20.04  |
| Web browser and version| Latest Chrome |
| Extensions installed | None |
| Browser tweaks | None |
| CryptPad version | Latest Docker - https://github.com/xwiki-labs/cryptpad-docker |

**Comment by promasu** [comment]
Can't reproduce with the given information.
Working fine with `docker run -p 3000:3000 -p 3001:3001 promasu/cryptpad:v5.1.0`

**Comment by aconite33** [comment]
Did you change the default drive size to 1 GB?
