### ISSUE TITLE
Update to latest version 3.23.0

### ISSUE THREAD

**Issue by ineiti** [xwiki-labs/cryptpad-docker#6]
It seems that the latest tag for cryptpad is v3.23.0, while the latest docker is at v3.21.0. What is your update policy?

**Comment by promasu** [comment]
Normally i push the images short after release of a new version but for personal reasons i did not yet had time for that. I scheduled it for later this day

**Comment by ineiti** [comment]
Cool - thanks a lot. Currently I updated it locally and it works fine...

**Comment by ansuz** [comment]
We plan to release v3.23.1 early tomorrow to address some minor issues that we noticed after deploying 3.23.0. I'd recommend waiting until then to tag.

**Comment by promasu** [comment]
Image is pushed
