### ISSUE TITLE
Usage of Docker Hub

### ISSUE THREAD

**Issue by artemislena** [xwiki-labs/cryptpad-docker#65]
L: Uhm, Docker Hub is apparently discontinuing its free tier: https://hacky.town/@rtyler/110023261891172425

Now, currently this is hosted on Docker Hub, and uhm, we don't know whether @promasu is using a free account for that. If you're using a paid account, alright, just close this issue, if not, maybe uh, you would like to move to quay.io, or GHCR or so? They still offer unlimited public repos for free.

**Comment by artemislena** [comment]
L: Wait, just realized, that's for teams only, apparently; personal accounts are still a thing, so uh, guess this doesn't apply here? Still something you uh, might want to keep an eye on.

**Comment by promasu** [comment]
Hi. Thanks for this notice.
Yes this image is inside my personal DockerHub account thus the problems don't apply here :)
